/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.1
  Forc version: 0.69.1
  Fuel-Core version: 0.45.1
*/

export { Contract } from './Contract';
export { ContractFactory } from './ContractFactory';
