export const styles = {
  root: {
    display: "grid",
    placeItems: "center",
    minHeight: "100vh",
    width: "100vw",
    backgroundColor: "black",
  },
  container: {
    color: "#ffffffec",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px",
    gap: "16px",
  },
  header: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    maxWidth: "960px",
  },
  menuBar: {
    width: "100%",
    maxWidth: "960px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "12px",
  },
  nav: {
    display: "flex",
    gap: "12px",
  },
  link: {
    color: "#fff",
    textDecoration: "none",
    backgroundColor: "#333",
    padding: "8px 12px",
    borderRadius: "6px",
  },
  label: {
    fontSize: "28px",
  },
  button: {
    borderRadius: "8px",
    margin: "24px 0px",
    backgroundColor: "#707070",
    fontSize: "16px",
    color: "#ffffffec",
    border: "none",
    outline: "none",
    height: "44px",
    padding: "0 1rem",
    cursor: "pointer",
  },
  input: {
    marginTop: "8px",
    marginBottom: "0px",
    height: "40px",
    borderRadius: "6px",
    padding: "0 0.5rem",
    border: "1px solid #444",
    backgroundColor: "#1a1a1a",
    color: "#ffffffec",
    width: "280px",
    display: "block",
  },
  footer: {
    position: "fixed",
    bottom: "12px",
    left: 0,
    right: 0,
    textAlign: "center",
    color: "#aaa",
    fontSize: "12px",
    padding: "4px 8px",
  },
};
